module.exports = {
    ERROR_NAME: 'Chiều dài từ %d đến %d ký tự!',
    ERROR_CATEGORY: 'Loại phục trang phải được chọn!',
    ERROR_BRAND: 'Thương hiệu phải được chọn!',
    ERROR_GENDER: 'Giới tính phải được chọn!',
    ERROR_STATUS: 'Trạng thái phải được chọn!',
    ERROR_SIZE: 'Kích cỡ phải được chọn!',
    ERROR_INPUT: 'Phải nhập vào!',
    ERROR_TIME: 'Thời điểm xuất bản phải được chọn!',
    ERROR_FILE_LIMIT: 'Kích thước file không phù hợp!',
    ERROR_FILE_REQUIRE: 'Vui lòng chọn file upload!',
    ADD_SUCCESS: 'Thêm mới thành công!',
    EDIT_SUCCESS: 'Cập nhật thành công!',
    DELETE_SUCCESS: 'Xóa thành công!',
    ERROR_FILE_EXTENSION: 'Phần mở rộng file không hợp lệ!',
    CHANGE_STATUS_SUCCESS: 'Cập nhật trạng thái thành công!',
    BROWSE_SUCCESS: 'Duyệt bài viết thành công!',
    REFUSE_SUCCESS: 'Từ chối bài viết thành công!',
    ERROR_LOGIN: 'Thông tin đăng nhập không chính xác!',
    ERROR_REGISTER: 'Email hoặc mật khẩu đã tồn tại!',
    ERROR_CONFIRM_PASSWORD: 'Mật khẩu và Xác nhận mật khẩu phải giống nhau!',
    ERROR_FORGET_PASSWORD: 'Thông tin nhập vào không chính xác!',
    ERROR_CHANGE_PASSWORD: 'Thông tin nhập vào không chính xác!',
    ERROR_INFO: 'Email đã tồn tại!'
}